config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :create, :new, :show] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create, :destroy]
  end
end
root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    user.update(posts_counter: user.posts.count)
  end

  def recent_5_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_3_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[name email password]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    post = Post.find(params[:post_id])
    render json: post.comments
  end

  def new
    @comment = Comment.new
    render :new
  end

  def create
    comment_author = current_user
    post = Post.find(params[:post_id])
    post_author = post.user

    comment = params[:comment]

    new_comment = Comment.new(comment.permit(:text))
    new_comment.post = post
    new_comment.user = comment_author

    return unless new_comment.save

    respond_to do |format|
      format.html do
        flash[:notice] = 'You commented.'
        redirect_to user_post_url(post_author, post)
      end
      format.json do
        render json: new_comment
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.includes(:user).find(params[:post_id])
    @post_author = @post.user

    @the_user = current_user

    @liked_posts_by_this_user = Like.where(user: @the_user, post: @post)

    destroy && return if @liked_posts_by_this_user.present?

    new_like = Like.create(user: @the_user, post: @post)

    return unless new_like.save

    flash[:notice] = 'Liked post.'
    redirect_back_or_to user_post_url(@post_author, @post)
  end

  def destroy
    @liked_posts_by_this_user.destroy_all
    flash[:notice] = 'Like removed.'
    redirect_back_or_to user_post_url(@post_author, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id)
  end

  def create
    post = params[:post]
    user = current_user

    new_post = Post.new(post.permit(:title, :text))
    new_post.comments_counter = 0
    new_post.likes_counter = 0
    new_post.user = user

    if new_post.save
      flash[:notice] = 'Successfully created a new post.'
      redirect_to user_post_url(user, new_post)
    else
      flash[:error] = 'Failed to create new post!'
      @post = new_post
      render :new
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def show
    @post = Post.includes(:user, comments: [:user]).find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to new_user_session_path if current_user.nil?

    @users = User.all
    # respond_to do |format|
    #   format.html
    #   # format.json { render json: @user }
    # end
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_3_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<%= form_with model: comment, url: user_post_comments_url(user, post), class: 'form' do |f| %>
  <%= f.text_area :text %>
  <%= f.submit "Comment" %>
<% end %>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Magic Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'home page', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
  <br/>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

app/views/likes/_like_button.html.erb
<%= form_with model: like, url: user_post_likes_url(user, post), method: :post, class: 'inline' do |f| %>
  <%= f.submit "#{post.likes_counter || 0} Likes", class: 'like-button' %>
<% end %>

app/views/others/_flash.html.erb
<div class="<%="flash flash-#{name}"%>">
  <%= msg%>
  <button type="button" class="action-button" onclick="this.parentElement.remove()">
    <svg class="action-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
  </button>
</div>

app/views/posts/_post.html.erb
<div class="post-card">
  <%= link_to user_post_path(post.user, post) do %>
    <h3><%= post.title%></h3>
  <% end %>
  <p><%= post.text.length > 100 ? post.text.first(100) + '...' : post.text %></p>
  <div class="post-card-meta">
    <%= render partial: "likes/like_button", locals: { like: Like.new, user: post.user, post: post } %>
    |
    <span><%= post.comments_counter || 0 %> Comments</span>
  </div>

  <% if local_assigns.include?(:comments) && comments.present? %>
    <div class="comments-wrapper">
      <h4>Recent comments:</h4>
      <% comments.each do |comment| %>
        <div class="comment-card">
          <strong><%= comment.user.name %>:</strong>
          <%= comment.text %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/_post_card.html.erb
<div class="post-card">
  <%= link_to user_post_path(post.user, post) do %>
    <h3><%= post.title%></h3>
  <% end %>
  <p><%= post.text.length > 100 ? post.text.first(100) + '...' : post.text %></p>
  <div class="post-card-meta">
    <%= render partial: "likes/like_button", locals: { like: Like.new, user: post.user, post: post } %>
    |
    <span><%= post.comments_counter || 0 %> Comments</span>
  </div>

  <% if local_assigns.include?(:comments) && comments.present? %>
    <div class="comments-wrapper">
      <h4>Recent comments:</h4>
      <% comments.each do |comment| %>
        <div class="comment-card">
          <strong><%= comment.user.name %>:</strong>
          <%= comment.text %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
Hello Post

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= form_with model: @post, url: user_posts_url, method: :post, class: 'form' do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title %>
  <%= f.label :text, 'Content' %>
  <%= f.text_area :text %>
  <%= f.submit "Save" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div><em>
  by
  <%= link_to user_path(@post.user) do %>
    <%= @post.user.name-%>
  <% end %>
  |
  <%= render partial: "likes/like_button", locals: { like: Like.new, user: @post.user, post: @post } %>
  |
  <span><%= @post.comments_counter || 0 %> Comments</span>
</em></div>
<p><%= @post.text %></p>

<hr />

<div class="comments-wrapper">
  <h3>Comments:</h3>
  <% if @post.comments.empty? %>
    <p>There no comment so far!</p>
  <% end %>
  <% @post.comments.each do |comment| %>
    <div class="comment-card">
      <strong>
        <%= link_to user_path(comment.user) do %>
          <%= comment.user.name %>
        <% end %>
        :
      </strong>
      <%= comment.text %>
    </div>
  <% end %>

  <h3>Add new comment:</h3>
  <%= render partial: "comments/comment_form", locals: { comment: Comment.new, user: @post.user, post: @post } %>
</div>

app/views/users/_card.html.erb
<div class="post-card">
 hello world <%= link_to user_post_path(post.user, post) do %>
  <h3><%= post.title%></h3>
<% end %>
<p><%= post.text.length > 100 ? post.text.first(100) + '...' : post.text %></p>
<div class="post-card-meta">
  <%= render partial: "likes/like_button", locals: { like: Like.new, user: post.user, post: post } %>
  |
  <span><%= post.comments_counter || 0 %> Comments</span>
</div>

<% if local_assigns.include?(:comments) && comments.present? %>
  <div class="comments-wrapper">
    <h4>Recent comments:</h4>
    <% comments.each do |comment| %>
      <div class="comment-card">
        <strong><%= comment.user.name %>:</strong>
        <%= comment.text %>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/users/_user.html.erb
<div class="user-card">
<img src="<%= user.photo %>" class="user-image" />
  <div class="user-detail">
    <h3><%= user.name %></h3>
    <div>Number of posts: <%= user.posts_counter || 0 %></div>
  </div>
</div>

app/views/users/_user_card.html.erb
<div class="user-card">
  <img src="<%=user.photo%>" class="user-image" />
  <div class="user-detail">
    <h3><%= user.name %></h3>
    <div>Number of posts: <%= user.posts_counter || 0 %></div>
  </div>
</div>

app/views/users/index.html.erb
<h1>List of users</h1>

<div class="users-list">
  <% @users.each do |user| %>
    <%= link_to user do %>
      <%= render user %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name %> User Details </h1>

<%= render @user %>

<div class="card-list">
  <h2>Bio:</h2>
  <p><%= @user.bio %></p>
</div>

<h2>Last three posts:</h2>

<div class="card-list">
  <% @recent_posts.each do |post| %>
    <div class="posts">
  <%= link_to user_post_path(post.user_id, post.id) do %>
    <h4><%=post.title%></h4>
  <% end %>
  <p><%=post.text%></p>
  <p>
    <span>
    Comments: <%= post.comments_counter ? post.comments_counter : 0 %>
    </span>
    <span>
    likes: <%= post.likes_counter ? post.likes_counter : 0 %>
    </span>
  </p>
</div>

  <% end %>
</div>


<button><%= link_to "See all posts", user_posts_path(@user.id) %></button>